"""Shared interception mechanics for the worker-side RL pipelines.

Every RL pipeline subclass follows the same protocol around upstream's
``forward``:

- **install** (once, idempotent): add machinery — swap the scheduler, wrap an
  upstream method with a tap or an injector.
- **arm** (every request): set the state the machinery uses THIS time — the
  SDE strength/gate, this request's x_T, a fresh capture buffer. Pipelines
  are long-lived worker singletons; anything not re-armed leaks across
  requests.
- run: upstream's stages execute; the installed taps/injectors fire at
  upstream-chosen moments.
- **harvest** (after): export the recordings onto the wire —
  ``DiffusionOutput.trajectory_*`` and ``custom_output`` are the only
  carriers that survive the worker→driver IPC boundary (plain runtime attrs
  are filtered).

This module holds the byte-identical mechanics of that protocol; the
per-family payloads (what a conditioning tap extracts, which upstream method
it wraps) stay in the family modules. vllm-omni-free on purpose — wire
objects are duck-typed ``Any`` — so the helpers are CPU-importable and
unit-tested without the runtime
(``tests/rollout/vllm_omni/test_pipeline_interception.py``).
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Tuple

import torch

from unirl.rollout.engine.vllm_omni.pipelines._shared.flow_match_sde_scheduler import (
    FlowMatchSDEDiscreteScheduler,
)
from unirl.types.noise_recipe import NoiseRecipe


def detach_cpu(t: Any) -> Any:
    """Detach + move to CPU for IPC transport. ``None``/non-tensor passthrough."""
    if isinstance(t, torch.Tensor):
        return t.detach().to("cpu")
    return t


def detach_cpu_pair(p: Any) -> Any:
    """``(cos, sin)`` rope-cache pair handler. Pass-through otherwise."""
    if isinstance(p, tuple) and len(p) == 2:
        return (detach_cpu(p[0]), detach_cpu(p[1]))
    return p


def stamp_custom_output(out: Any, key: str, value: Any) -> None:
    """Write onto ``DiffusionOutput.custom_output``.

    ``custom_output`` is the dataclass-declared dict vllm-omni explicitly
    forwards into ``OmniRequestOutput.custom_output`` (upstream
    ``diffusion/data.py``, ``stage_diffusion_proc.py``); plain runtime attrs
    set on ``DiffusionOutput`` get filtered during IPC — this is the only
    legal export path besides the ``trajectory_*`` fields.
    """
    if out.custom_output is None:
        out.custom_output = {}
    out.custom_output[key] = value


def drain_trajectory_into(out: Any, scheduler: Any) -> None:
    """Harvest the SDE scheduler's per-request recordings onto the wire.

    ``trajectory_timesteps`` carries the **true [0, 1] sigma schedule** —
    what the driver reads back as ``LatentSegment.sigmas`` and what replay
    indexes per step. The original 1000-scale per-step timesteps are dropped
    (trivially regenerable from σ). The real sparse SDE step ids ride
    ``custom_output["sde_step_indices"]`` so the response layer can echo
    them as the segment's ``sde_indices``.
    """
    traj = scheduler.drain_trajectory()
    if traj is None:
        return
    latents, sigmas, _timesteps, log_probs = traj
    out.trajectory_latents = latents
    out.trajectory_timesteps = sigmas
    out.trajectory_log_probs = log_probs
    stamp_custom_output(out, "sde_step_indices", scheduler.last_sde_step_indices)


def resolve_request_noise(req: Any, *, caller: str) -> Optional[torch.Tensor]:
    """This request's driver-authored x_T, or ``None`` (upstream RNG fires).

    Two transports (see ``utils/noise.pack_initial_noise_extra_args``):

    - a materialized ``initial_noise_batch`` ``[B, ...]`` tensor shared
      across the prompt batch (Omni broadcasts one sampling-params object to
      every request of a generate call);
    - the x_T RECIPE (``init_noise_group_ids`` + ``init_noise_latent_shape``
      + ``init_noise_seed``), regenerated byte-identically on CPU-fp32
      (``generate_shared_noise`` keys each gid by its own seeded generator,
      so regenerating only ``gids[idx]`` reproduces row ``idx`` exactly).

    Either way the request's row is picked by the ``f"{i}_{uuid}"``
    request-id index prefix (``vllm_omni/.../entrypoints/omni.py``). The
    returned slice keeps its leading batch dim ``[1, ...]`` — upstream's
    ``prepare_latents`` batch shape is what the denoise loop expects
    (``num_outputs_per_prompt=1``).
    """
    extra = getattr(req.sampling_params, "extra_args", None) or {}
    noise_batch = extra.get("initial_noise_batch")
    recipe_gids = extra.get("init_noise_group_ids")
    if noise_batch is None and not recipe_gids:
        return None

    rid = str(getattr(req, "request_id", "") or "")
    try:
        idx = int(rid.split("_", 1)[0])
    except ValueError:
        raise RuntimeError(
            f"{caller}: cannot parse batch index from request_id={rid!r}. Expected Omni's ``f'{{i}}_{{uuid}}'`` shape."
        )

    if noise_batch is not None:
        if idx < 0 or idx >= int(noise_batch.shape[0]):
            raise IndexError(
                f"{caller}: index {idx} out of bounds for noise_batch.shape[0]={int(noise_batch.shape[0])}."
            )
        return noise_batch[idx : idx + 1].clone()

    if idx < 0 or idx >= len(recipe_gids):
        raise IndexError(f"{caller}: index {idx} out of bounds for init_noise_group_ids len={len(recipe_gids)}.")
    return NoiseRecipe(
        noise_group_ids=[str(recipe_gids[idx])],
        base_seed=int(extra.get("init_noise_seed", 0)),
        latent_shape=tuple(extra["init_noise_latent_shape"]),
    ).resolve()  # [1, ...] — matches the noise_batch[idx:idx+1] slice shape


def inject_latents(
    args: Tuple[Any, ...],
    kwargs: Dict[str, Any],
    noise: torch.Tensor,
    *,
    dtype_idx: int = 4,
    device_idx: int = 5,
    latents_idx: int = 7,
) -> Tuple[Tuple[Any, ...], Dict[str, Any]]:
    """Slot a pre-computed x_T into a ``prepare_latents`` call site.

    Upstream calls ``prepare_latents`` with **all args positional** and the
    sd3/hv15 pipelines share the slot layout (dtype@4, device@5, latents@7).
    Writing ``kwargs["latents"]`` while ``latents`` is already positional
    raises ``TypeError: got multiple values for argument 'latents'`` — so
    replace the positional slot in place, and fall back to the keyword only
    for partial call shapes. The noise is moved to the call site's
    dtype/device first.
    """
    dtype = args[dtype_idx] if len(args) > dtype_idx else kwargs.get("dtype")
    device = args[device_idx] if len(args) > device_idx else kwargs.get("device")
    if dtype is not None:
        noise = noise.to(dtype=dtype)
    if device is not None:
        noise = noise.to(device=device)
    if len(args) >= latents_idx + 1:
        args = (*args[:latents_idx], noise, *args[latents_idx + 1 :])
    else:
        kwargs = {**kwargs, "latents": noise}
    return args, kwargs


def make_sde_scheduler(upstream_config: Any, *, eta: float = 0.0) -> FlowMatchSDEDiscreteScheduler:
    """Build the trajectory-capturing scheduler from the upstream scheduler's
    config — the sd3/hv15 install path (hi3 constructs with explicit HI3
    kwargs and routes through the inner pipeline's ``set_scheduler``).

    ``from_config`` on a ``SchedulerMixin`` subclass re-invokes ``__init__``
    with the same kwargs the parent was built with (dynamic shifting keeps
    working), plus our ``eta`` — which ``scheduler.arm`` retunes per request
    anyway.
    """
    return FlowMatchSDEDiscreteScheduler.from_config(upstream_config, eta=float(eta))


__all__ = [
    "detach_cpu",
    "detach_cpu_pair",
    "drain_trajectory_into",
    "inject_latents",
    "make_sde_scheduler",
    "resolve_request_noise",
    "stamp_custom_output",
]
